name = "InnoCraft"
author = "Jandro5vq"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11465edbc8d9fa6f55f83e3f7a7ab7ddea4eef269970e434355ff612e87f8c80"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
