name = "InnoCraft"
author = "Jandro5vq"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a14969afc8c742083c6e3cf4cc981709e68a5cd6cca239c933b76404aa613fb7"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
